services:
  app:
    build: .
    container_name: order-matching-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - test-postgres
    networks:
      - order-network
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: order-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Puneet
      POSTGRES_DB: order-matching-engine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - order-network

  test-postgres:
    image: postgres:15
    container_name: order-test-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: order-matching-test
    networks:
      - order-network

networks:
  order-network:
    driver: bridge
